- name: "Jenkins apt-key is present"
  apt_key:
    url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    state: present
  tags: [jenkins]

- name: "Jenkins repository is present"
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/debian-stable binary/'
    state: present
  tags: [jenkins]

- name: "Jenkins is installed"
  apt:
    name: jenkins
    state: installed
  register: jenkins_result
  tags: [jenkins]

- name: "Jenkins is started and runs on boot"
  service:
    name: jenkins
    state: started
    enabled: yes

- name: "Pause 180 seconds for jenkins to start"
  pause: seconds=180
  when: jenkins_result|changed
  tags: [jenkins]
