- name: "Plugins are installed"
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ ip }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  register: plugins_result
  tags: [jenkins]

- name: "Wait for plugins installation completed"
  wait_for:
    path: /var/lib/jenkins/plugins/{{ item }}
  with_items: plugins
  timeout: 600
  tags: [jenkins]

- name: "Jenkins is reloaded"
  uri:
    url: http://{{ ip }}:8080/restart
    method: POST
    status_code: 200,302
  when: plugins_result|changed
  ignore_errors: yes
  tags: [jenkins]

- name: "Pause 120 seconds for jenkins relload complete"
  pause: seconds=120
  when: plugins_result|changed
  tags: [jenkins]