- name: DockerUI is running
  docker:
    image: hypriot/rpi-dockerui
    name: dockerui
    ports: 9000:9000
    privileged: yes
    state: running
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  register: container_result
  tags: [docker-ui]

- pause: seconds=30
  when: container_result|changed
  tags: [docker-ui]