- set_fact:
    my_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: "User {{user_name}} has authorized keys set"
  authorized_key:
    user: "{{user_name}}"
    key:  "{{ lookup('file', my_ssh_key) }}"
  tags: [common]

# has to be the last one, due to password change
- name: "User {{user_name}} has  password"
  user:
    name: "{{user_name}}"
    password: "{{user_password}}"
    shell: /bin/bash
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
  tags: [common]

