---
- name: "rsync is present"
  package: name=rsync state=present
  tags: [bash]

- name: "Copy bash-it files"
  synchronize:
    src: bash_it/
    dest: "/home/{{user_name}}/.bash_it"
    archive: yes
    delete: yes
    recursive: true
    mode: push
  tags: [bash]

- name: "Update .bashrc file"
  template: src=bashrc dest=/home/{{user_name}}/.bashrc owner={{user_name}} group={{user_name}} mode=0644 backup=yes
  tags: [bash]
