- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: safe
  tags: [os]

- name: Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes
  tags: [os]

- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: safe
  tags: [os]

- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - htop
    - lynx
    - jq
    - unzip
  tags: [os]