- name: Update apt
  sudo: true
  apt: update_cache=yes cache_valid_time=3600
  tags: [os]

- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: safe
  tags: [os]

- name: Install dev tools
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - htop
    - lynx
    - jq
    - unzip
    - mc
    - curl
  tags: [os]