- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: safe
  tags: [os]

- name: Install tools
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - htop
    - lynx
    - jq
    - unzip
    - mc
    - curl
  tags: [os]

- name: Install dev tools
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - git
    - tig
  when: dev_node
  tags: [os]