- name: Set hosts
  template: src=hosts dest=/etc/hosts
  tags: [os]

- name: Set hostname
  hostname: name="{{ host_name }}"
  tags: [os]

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ host_name }}"
  tags: [os]
