ssh:
  pub_key_path: "~/.ssh/id_rsa.pub"

timezone: "Europe/Berlin"

hosts: [
  { host_ip: "192.168.178.200", host_name: "dc1-rpi0"},
  { host_ip: "192.168.178.201", host_name: "dc1-rpi1"},
  { host_ip: "192.168.178.202", host_name: "dc1-rpi2"},
  { host_ip: "192.168.178.203", host_name: "dc1-rpi3"},
  { host_ip: "192.168.178.204", host_name: "dc1-rpi4"}
]