jenkins_home: /var/lib/jenkins

jobs: [
  {
    name: "sample",
    src: "jobs/sample-config.xml"
  }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
