jenkins_home: /var/lib/jenkins

configs: [
  { src: "hudson.tasks.Maven.xml", dir: "/var/lib/jenkins", file: "hudson.tasks.Maven.xml", mode: "0777" }
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
