- name: Set '/etc/os-release'
  copy:
    src: os-release
    dest: /etc/os-release
  tags: [docker]

- name: Add Hypriot Repo via script
  script: hypriot_packagecloud.sh

- name: Docker Hypriot is present
  apt:
    name: docker-hypriot
    state: latest
    force: yes
  tags: [docker]

- name: Python is present
  apt:
    name: python
    state: latest
    force: yes
  tags: [docker]

- name: Outdated python-pip is absent
  apt:
    name: python-pip
    state: absent
  tags: [docker]

- name: Python setuptools are present
  apt:
    name: python-setuptools
    state: latest
    force: yes
  tags: [docker]

- name: Latest python-pip is present
  easy_install:
    name: pip
    state: latest
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    state: present
  tags: [docker]

- name: Debian files are present
  copy:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_docker_cfg
  tags: [docker]

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_docker_cfg|changed
  tags: [docker]

- name: Docker service is restarted
  service:
    name: docker
    enabled: yes
    state: restarted
  tags: [docker]
