- name: Add Hypriot Repo Key
  apt_key: url=https://packagecloud.io/gpg.key

- name: Add Hypriot Repo and update cache
  apt_repository:
    repo: deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker Hypriot is present
  apt:
    name: docker-hypriot
    state: latest
    force: yes
  tags: [docker]

- name: Python is present
  apt:
    name: python
    state: latest
    force: yes
  tags: [docker]

- name: Outdated python-pip is absent
  apt:
    name: python-pip
    state: absent
  tags: [docker]

- name: Python setuptools are present
  apt:
    name: python-setuptools
    state: latest
    force: yes
  tags: [docker]

- name: Latest python-pip is present
  easy_install:
    name: pip
    state: latest
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker-py
    state: present
  tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: /lib/systemd/system/docker.service
  register: copy_result
  tags: [docker]

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed
  tags: [docker]

- name: Docker service is restarted
  service:
    name: docker
    enabled: yes
    state: restarted
  tags: [docker]

- name: Swarm node is running
  docker:
    name: swarm-node
    image: hypriot/rpi-swarm
    command: join --advertise={{ ip }}:2375 consul://{{ ip }}:8500/swarm
    env:
      SERVICE_NAME: swarm-node
  when: not swarm_master is defined
  tags: [swarm]

- name: Swarm master is running
  docker:
    name: swarm-master
    image: hypriot/rpi-swarm
    ports: 2375:2375
    command: manage consul://{{ ip }}:8500/swarm
    env:
      SERVICE_NAME: swarm-master
  when: swarm_master is defined
  tags: [swarm]

